version: "1.1"

services:
  node:
    container_name: reja
    restart: always
    image: tokhirbek97/reja-image
    ports:
      - 3005:6006
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app

    networks:
      - reja_network

    command: bash -c "npm install && npm run dev"

networks:
  reja_network:
    driver: bridge